import type { Metadata } from "next";
import { Montserrat, Dynalight, Abril_Fatface } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import TopBar from "@/components/TopBar";

const abrilFatface = Abril_Fatface({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-abril-fatface",
});
const montserratNormal = Montserrat({
  subsets: ["latin"],
  style: "normal",
  variable: "--font-montserrat-normal",
});

const montserratItalic = Montserrat({
  subsets: ["latin"],
  style: "italic",
  variable: "--font-montserrat-italic",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${abrilFatface.variable} ${montserratNormal.variable} ${montserratItalic.variable} h-full antialiased`}
    >
      <body className="min-h-full font-montserrat bg-zinc-50 text-zinc-800">
        <TopBar />
        <main className="mx-auto max-w-7xl w-full px-6">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
