import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import TopBar from "@/components/TopBar";

// 1. Load all normal weights (Variable font handles this automatically)
const montserratNormal = Montserrat({
  subsets: ["latin"],
  style: "normal",
  variable: "--font-montserrat-normal",
});

// 2. Load all italic weights
const montserratItalic = Montserrat({
  subsets: ["latin"],
  style: "italic",
  variable: "--font-montserrat-italic",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${montserratNormal.variable} ${montserratItalic.variable} h-full antialiased`}
    >
      <body className="min-h-full font-montserrat">
        <TopBar />
        <main className="mx-auto max-w-7xl w-full px-6">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
